'use client';
import { useCallback,useEffect,useLayoutEffect,useRef,useState } from 'react';
import { Bell,Menu,Minus,Square,X,Users,Paperclip,Smile,Video,Search,Link2,Check,LogOut,Play,Pause,MessageSquare,Type,ChevronRight,ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { initials } from '@/lib/words';
import MessengerHome,{Portrait} from '@/components/messenger-home';
import type { Room } from '@/lib/game';
type View=Omit<Room,'players'> & {players:(Room['players'][number]&{online:boolean;photoId?:string|null})[];serverTime:number;wordCount:number};
export default function Home(){
 const [hub,setHub]=useState(true),[uploading,setUploading]=useState(false),[room,setRoom]=useState<View|null>(null),[token,setToken]=useState(''),[name,setName]=useState(''),[code,setCode]=useState(''),[draft,setDraft]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[menu,setMenu]=useState(false),[people,setPeople]=useState(false),[chat,setChat]=useState(false),[quiet,setQuiet]=useState(false),[wide,setWide]=useState(false),[copied,setCopied]=useState(false),[search,setSearch]=useState(''),[showSearch,setShowSearch]=useState(false),[now,setNow]=useState(Date.now()),[offset,setOffset]=useState(0),[connected,setConnected]=useState(true),[font,setFont]=useState(false),[seconds,setSeconds]=useState(15),[vocabulary,setVocabulary]=useState<'basic'|'extended'>('extended');
 const hubView=useRef(true),quietView=useRef(false);hubView.current=hub;quietView.current=quiet;
 const saveName=useCallback((value:string)=>{setName(value);localStorage.setItem('chat-name',value);},[]);
 const fileInput=useRef<HTMLInputElement>(null);
 const conversation=useRef<HTMLDivElement>(null),scrollPosition=useRef({roomId:'',top:0,atBottom:true}),input=useRef<HTMLTextAreaElement>(null),resuming=useRef(false),polling=useRef(false),actionBusy=useRef(false),requestSequence=useRef(0),appliedSequence=useRef(0),view=useRef<View|null>(null);view.current=room;
 const myId=token.slice(0,8),me=room?.players.find(p=>p.id===myId),host=room?.host===myId,isTurn=room?.phase==='playing'&&room.turn===myId;
 const send=useCallback(async(action:string,extra:Record<string,unknown>={},silent=false)=>{
  if(!token)return null; const sequence=++requestSequence.current;
  if(!silent){actionBusy.current=true;setBusy(true);setError('');}
  try{
   const res=await fetch('/api/rooms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token,room:view.current?.id??code,viewing:!hubView.current&&!quietView.current,...extra}),signal:AbortSignal.timeout(10000)});
   const data=await res.json() as View & {error?:string};if(!res.ok)throw new Error(data.error??'연결하지 못했습니다.');
   if(sequence>=appliedSequence.current){appliedSequence.current=sequence;setRoom(data);setSeconds(data.seconds);setVocabulary(data.vocabulary??'extended');setOffset(data.serverTime-Date.now());}setConnected(true);
   if(['create','join'].includes(action)){sessionStorage.setItem('room',data.id);if(document.documentElement.dataset.desktop==='true')localStorage.setItem('desktop-room',data.id);localStorage.setItem('chat-name',String(extra.name??name));const url=new URL(location.href);url.searchParams.set('room',data.id);if(location.href!==url.href)history.pushState(null,'',url);setMenu(false);}
   return data;
  }catch(e){if(!silent)setError(e instanceof Error?e.message:'연결하지 못했습니다.');else setConnected(false);return null;}
  finally{if(!silent){actionBusy.current=false;setBusy(false);}}
 },[token,code,name]);
 useEffect(()=>{const desktop=new URLSearchParams(location.search).get('desktop')==='1';if(desktop){document.documentElement.dataset.desktop='true';document.title='대화 · OfficeChat';}const tokenStore=localStorage;let t=tokenStore.getItem('chat-token')??sessionStorage.getItem('chat-token');if(!t){t=typeof crypto.randomUUID==='function'?crypto.randomUUID():'10000000-1000-4000-8000-100000000000'.replace(/[018]/g,c=>(Number(c)^(crypto.getRandomValues(new Uint8Array(1))[0]&15)>>(Number(c)/4)).toString(16));tokenStore.setItem('chat-token',t);}tokenStore.setItem('chat-token',t);setToken(t);if(new URLSearchParams(location.search).get('room'))setHub(false);setName(localStorage.getItem('chat-name')??'');setCode(new URLSearchParams(location.search).get('room')??(desktop?localStorage.getItem('desktop-room'):sessionStorage.getItem('room'))??'');},[]);
 useEffect(()=>{if(!token||resuming.current||!name)return;resuming.current=true;const invited=new URLSearchParams(location.search).get('room');if(invited)void send('join',{room:invited,name}).then(r=>{if(r)setHub(false);});else{const saved=sessionStorage.getItem('room')??localStorage.getItem('desktop-room');if(saved)void send('join',{room:saved,name},true).then(()=>{const url=new URL(location.href);url.searchParams.delete('room');history.replaceState(null,'',url);});}},[token,name,send]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),200);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!room)return;const timer=setInterval(async()=>{if(polling.current||actionBusy.current)return;polling.current=true;await send('poll',{},true);polling.current=false;},1000);return()=>clearInterval(timer);},[room?.id,send]);
 useLayoutEffect(()=>{
  const el=conversation.current;if(!el||!room)return;
  const saved=scrollPosition.current;
  if(saved.roomId!==room.id){saved.roomId=room.id;saved.top=0;saved.atBottom=true;}
  el.scrollTop=saved.atBottom?el.scrollHeight:saved.top;
  saved.top=el.scrollTop;
 },[quiet,hub,room?.id,room?.messages.at(-1)?.id]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){setQuiet(q=>!q);setMenu(false);setPeople(false);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 const openRoom=async(id:string,direct=false)=>{const r=await send('join',{room:id,name});if(!r)throw new Error('대화방에 연결하지 못했습니다. 코드를 확인해 주세요.');if(r){setHub(false);setChat(direct||!!r.direct);setDraft('');setSearch('');setShowSearch(false);setPeople(false);}};
 const backToList=()=>{setHub(true);setMenu(false);setPeople(false);setError('');const url=new URL(location.href);url.searchParams.delete('room');history.replaceState(null,'',url);};
 useEffect(()=>{const back=()=>{const id=new URLSearchParams(location.search).get('room');if(!id)setHub(true);else if(id===view.current?.id)setHub(false);else void send('join',{room:id,name}).then(r=>{if(r)setHub(false);});};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);},[name,send]);
 const transmit=async()=>{if(!draft.trim()||busy)return;const result=await send(chat||room?.phase!=='playing'?'chat':'word',{text:draft});if(result){setDraft('');input.current?.focus();}};
 const upload=async(file?:File)=>{
  if(!file||!room||uploading)return;
  if(file.size>512*1024){setError('파일은 512KB 이하로 첨부해 주세요.');return;}
  setUploading(true);setError('');
  try{const form=new FormData();form.append('token',token);form.append('room',room.id);form.append('file',file);
   const res=await fetch('/api/files',{method:'POST',body:form,signal:AbortSignal.timeout(30000)});const data=await res.json() as {id:string;error?:string};
   if(!res.ok)throw new Error(data.error??'파일을 첨부하지 못했습니다.');
   await send('attachment',{fileId:data.id});
  }catch(e){setError(e instanceof Error?e.message:'파일을 첨부하지 못했습니다.');}
  finally{setUploading(false);if(fileInput.current)fileInput.current.value='';}
 };
 const copy=async()=>{try{await navigator.clipboard.writeText(`${location.origin}/?room=${room?.id}`);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{setError('주소창의 링크를 복사해 주세요.');}};
 const remaining=Math.min(Math.max(3,(room?.seconds??15)-Math.floor((room?.turnCount??0)/10)),Math.max(0,Math.ceil(((room?.deadline??0)-(now+offset))/1000)));
 const player=room?.players.find(p=>p.id===room.turn);
 const stamp=(time:number)=>{const parts=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'numeric',minute:'2-digit',hour12:true}).formatToParts(time);const get=(type:string)=>parts.find(p=>p.type===type)?.value;return `${get('year')}-${get('month')}-${get('day')} ${get('dayPeriod')} ${get('hour')}:${get('minute')}`;};
 if(quiet)return <main className="cover" onDoubleClick={()=>setQuiet(false)}><header>대화 <Button variant="ghost" size="icon" aria-label="대화창 복원" onClick={()=>setQuiet(false)}><MessageSquare/></Button></header><div className="cover-body">새 메시지가 없습니다.</div><footer>Esc 키를 눌러 대화창으로 돌아갑니다.</footer></main>;
 if(hub)return <main className={`workspace ${wide?'expanded':''}`}><MessengerHome token={token} name={name} onName={saveName} onOpen={openRoom} onCreate={async code=>{const r=await send(code?'join':'create',{name,...(code?{room:code}:{})});if(!r)throw new Error('대화방에 연결하지 못했습니다. 코드를 확인해 주세요.');if(r){setChat(!!r.direct);setHub(false);setDraft('');}}} onQuiet={()=>setQuiet(true)} onResize={()=>setWide(!wide)}/></main>;
 return <main className={`workspace ${wide?'expanded':''}`}>
  <section className={`messenger ${font?'large-text':''}`} aria-label="대화창">
   <header className="titlebar"><Button variant="ghost" size="icon-xs" aria-label="대화 목록으로" title="뒤로가기" onClick={backToList}><ArrowLeft size={15}/></Button><span className="names">{room?room.players.map(p=>p.name).join(', '):'대화'}</span><Button variant="ghost" className="member-button" size="sm" onClick={()=>{setPeople(!people);setMenu(false);}} aria-label="참여자"><Users size={13}/><span>{room?.players.length??0}</span></Button><div className="window-tools"><Button variant="ghost" size="icon-xs" aria-label="알림 상태" title={connected?'연결됨':'재연결 중'}><Bell size={13}/></Button><Button variant="ghost" size="icon-xs" aria-label="대화 메뉴" onClick={()=>{setMenu(!menu);setPeople(false);}}><Menu size={15}/></Button><i/><Button variant="ghost" size="icon-xs" aria-label="최소화" onClick={()=>setQuiet(true)}><Minus size={15}/></Button><Button variant="ghost" size="icon-xs" aria-label="크기 변경" onClick={()=>setWide(!wide)}><Square size={12}/></Button><Button variant="ghost" size="icon-xs" aria-label="대화창 접기" onClick={()=>setQuiet(true)}><X size={15}/></Button></div></header>
   {people&&room&&<div className="dropdown people"><div className="panel-title">참여자 <span>{room.players.length}</span></div>{room.players.map(p=><div className="person" key={p.id}><span className="avatar">{p.name[0]}</span><span>{p.name}{p.id===myId?' (나)':''}<small>{p.id===room.host?'방장 · ':''}{p.online?'접속 중':'자리 비움'}{room.phase==='playing'&&!p.alive?' · 관전':''}</small></span><span className="score">{p.score}</span></div>)}<Button variant="outline" className="full" onClick={copy}>{copied?<Check/>:<Link2/>}{copied?'복사됨':'초대 링크 복사'}</Button></div>}
   {menu&&room&&<div className="dropdown settings"><div className="panel-title">대화 설정 <span>{room.id}</span></div><Button variant="ghost" className="full" onClick={copy}><Link2/>{copied?'복사됨':'초대 링크 복사'}</Button>{host&&<><label className="setting-row">응답 시간<select value={seconds} disabled={room.phase==='playing'} onChange={async e=>{const value=Number(e.target.value);setSeconds(value);await send('settings',{seconds:value,vocabulary});}}>{[5,10,15,20,30].map(s=><option key={s} value={s}>{s}초</option>)}</select></label><label className="setting-row">단어 범위<select aria-label="단어 범위" value={vocabulary} disabled={room.phase==='playing'} onChange={async e=>{const value=e.target.value as 'basic'|'extended';setVocabulary(value);await send('settings',{seconds,vocabulary:value});}}><option value="basic">사전 명사 · 32,589개</option><option value="extended">확장 단어 · 211,277개</option></select></label><Button variant="outline" className="full" disabled={busy} onClick={()=>send(room.phase==='playing'?'stop':'start')}>{room.phase==='playing'?<Pause/>:<Play/>}{room.phase==='playing'?'잠시 쉬기':room.phase==='finished'?'다시 이어가기':'이어가기 시작'}</Button></>}<div className="rules">2명 이상 · 한글 2글자 이상 · 두음법칙 허용<br/>10턴마다 1초 감소, 최소 3초<br/>중복 금지 · 시간 초과 시 탈락<br/>확장 범위에는 인명·지명·작품명이 포함됩니다.<br/>미등록 단어는 방장 확인 후 추가 ({room.wordCount.toLocaleString()}개 등록)<br/>확인 중에도 제한시간은 흐릅니다.<br/><a href="/dictionary-sources.md" target="_blank" rel="noreferrer">단어 목록·출처</a></div><Button variant="ghost" className="full leave" onClick={async()=>{if(await send('leave')){setRoom(null);sessionStorage.removeItem('room');localStorage.removeItem('desktop-room');backToList();setMenu(false);setCode('');}}}><LogOut/>대화방 나가기</Button></div>}
   {!room?<div className="entrance"><div className="entrance-heading"><MessageSquare size={24}/><h1>대화 참여</h1></div><label htmlFor="name">이름</label><Input id="name" maxLength={20} placeholder="대화에 사용할 이름" value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&name.trim())send(code?'join':'create',{name});}}/><label htmlFor="room">대화방 코드</label><Input id="room" maxLength={8} placeholder="초대받은 코드 (없으면 새 대화)" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/>{error&&<p className="error" role="alert">{error}</p>}<Button className="enter" disabled={busy||!name.trim()} onClick={()=>send(code?'join':'create',{name})}>{busy?'연결 중…':code?'대화 참여':'새 대화 만들기'}<ChevronRight size={16}/></Button><p className="entry-note">같은 방 코드로 함께 접속할 수 있습니다.</p></div>:<>
    {showSearch&&<div className="search-row"><Search size={15}/><Input autoFocus placeholder="대화 내용 검색" value={search} onChange={e=>setSearch(e.target.value)}/><Button variant="ghost" size="icon-xs" aria-label="검색 닫기" onClick={()=>{setShowSearch(false);setSearch('');}}><X/></Button></div>}
    <div ref={conversation} className="conversation" tabIndex={0} role="log" aria-live="polite" onScroll={e=>{const el=e.currentTarget;scrollPosition.current={roomId:room.id,top:el.scrollTop,atBottom:el.scrollHeight-el.clientHeight-el.scrollTop<=8};}}><div className="date-divider">{new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric'}).format(room.created)}</div>{room.messages.filter(m=>!search||`${m.name} ${m.text}`.includes(search)).map(m=><div className={`message ${m.system?'system':''}`} key={m.id}><div className="metadata">{!m.system&&<Portrait name={m.name} photoId={room.players.find(p=>m.senderId?p.id===m.senderId:p.name===m.name)?.photoId}/>} [{stamp(m.time)}] {m.name}</div><div className="message-text">{m.attachment?<div className="attachment">{m.attachment.mime.startsWith('image/')&&<a href={`/api/files?id=${m.attachment.id}`} download><img src={`/api/files?id=${m.attachment.id}&preview=1`} alt={m.attachment.name} onLoad={()=>{const el=conversation.current;if(el&&scrollPosition.current.atBottom)el.scrollTop=el.scrollHeight;}}/></a>}<a className="attachment-file" href={`/api/files?id=${m.attachment.id}`} download><Paperclip size={14}/><span>{m.attachment.name}<small>{Math.ceil(m.attachment.size/1024)}KB · 다운로드</small></span></a></div>:m.text}</div></div>)}{room.phase==='waiting'&&room.players.length<2&&<div className="waiting-note">참여자를 기다리고 있습니다.<br/><button onClick={copy}>{copied?'복사했습니다.':'초대 링크 복사'}</button></div>}</div>
    <div className="statusbar"><span>{uploading?'파일 첨부 중…':!connected?'다시 연결하는 중…':room.phase==='playing'?`${player?.name}님 차례${room.last?` · ${initials(room.last.slice(-1)).join('/')} →`:''}`:room.phase==='finished'?'대화가 끝났습니다.':'참여 대기 중'}</span><span>{room.phase==='playing'?`${remaining}초`:host&&room.players.length>=2?<button disabled={busy} onClick={()=>send('start')}>이어가기</button>:`${room.players.length}명 참여`}</span></div>
    {room.pending&&<div className="pending"><span>‘{room.pending.word}’ 확인 대기</span>{host?<div><button disabled={busy} onClick={()=>send('approve',{approved:true,word:room.pending!.word})}>등록</button><button disabled={busy} onClick={()=>send('approve',{approved:false,word:room.pending!.word})}>반려</button></div>:<span>방장이 확인합니다.</span>}</div>}
    <input ref={fileInput} type="file" className="file-input" aria-label="첨부파일 선택" onChange={e=>void upload(e.target.files?.[0])}/><div className="toolbar"><Button variant="ghost" size="icon-sm" aria-label="파일 첨부" title="이미지·파일 첨부 (최대 512KB)" disabled={uploading||busy} onClick={()=>fileInput.current?.click()}><Paperclip/></Button><Button variant="ghost" size="icon-sm" aria-label="메시지 모드 전환" title={chat?'일반 대화 모드':'단어 입력 모드'} onClick={()=>{setChat(!chat);input.current?.focus();}}><MessageSquare className={chat?'active':''}/></Button><Button variant="ghost" size="icon-sm" aria-label="이모티콘" onClick={()=>{setDraft(d=>d+' :)');setChat(true);input.current?.focus();}}><Smile/></Button><Button variant="ghost" size="icon-sm" aria-label="글자 크기 변경" onClick={()=>setFont(!font)}><Type/></Button><Button variant="ghost" size="icon-sm" aria-label="대화창 접기" title="대화창 접기 (Esc)" onClick={()=>setQuiet(true)}><Video/></Button><Button variant="ghost" size="icon-sm" className="search-button" aria-label="대화 검색" onClick={()=>setShowSearch(!showSearch)}><Search/></Button></div>
    {error&&<div className="inline-error" role="alert">{error}<button aria-label="닫기" onClick={()=>setError('')}><X size={12}/></button></div>}
    <div className="composer"><Textarea ref={input} className="draft" aria-label={chat?'대화 메시지':'단어 입력'} value={draft} maxLength={500} placeholder={chat||room.phase!=='playing'?'':isTurn?'':me?.alive?'차례를 기다려 주세요':'관전 중 · 일반 대화로 전환할 수 있습니다'} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();transmit();}}}/><Button className="send" disabled={busy||!draft.trim()||(!chat&&room.phase==='playing'&&!isTurn)} onClick={transmit}>전송</Button></div>
   </>}
  </section>
 </main>;
}
