import {message,type Room} from '@/lib/game';
import {quizCategoryName,quizConfig,retiredQuizQuestion} from './config';
import {choseongHint,firstLetterHint,isCorrectAnswer} from './normalize';
import type {QuizQuestion,QuizSettings,QuizState,QuizStats,QuizView} from './types';
const freshStats=():QuizStats=>({correct:0,wrong:0,streak:0,bestStreak:0,responseTotal:0});
function log(room:Room,text:string){message(room,'알림',text,true);}
export function activeQuiz(room:Room){return !!room.quiz&&room.quiz.stage!=='finished';}
function beginQuestion(state:QuizState,now:number){state.stage='question';state.openedAt=now;state.deadline=now+quizConfig.revealAtMs;}
function openQuestion(room:Room,question:QuizQuestion,now:number){const state=room.quiz!;state.current=question;state.stage='ready';state.number++;state.openedAt=0;state.deadline=0;state.readyPlayers=[];state.readyDeadline=now+quizConfig.readyTimeoutMs;state.hintStage=0;state.attempts={};state.lastAttemptAt={};state.completedFingerprint='';state.historyRecorded=false;state.categoryHistory=[...state.categoryHistory,question.category].slice(-5);state.usedFingerprints.push(question.fingerprint);log(room,`[상식 퀴즈] ${state.questionCount?`${state.number}/${state.questionCount}`:`${state.number}번`}\n${question.question}`);}
export function startQuiz(room:Room,settings:QuizSettings,questions:QuizQuestion[],now:number){if(activeQuiz(room)||room.phase==='playing'||(room.infiltrator&&room.infiltrator.stage!=='finished'))throw new Error('이미 게임이 진행 중입니다.');const players=room.players.filter(player=>now-player.seen<15000);if(!players.length)throw new Error('접속 중인 참여자가 필요합니다.');if(!questions.length)throw new Error('사용할 수 있는 문제가 없습니다. 잠시 후 다시 시도해 주세요.');const stats=Object.fromEntries(players.map(player=>[player.id,freshStats()])),scores=Object.fromEntries(players.map(player=>[player.id,0]));room.quiz={...settings,id:crypto.randomUUID(),creator:room.host,players:players.map(({id,name})=>({id,name})),stage:'loading',number:0,queue:questions,cursor:0,current:null,openedAt:0,deadline:0,hintStage:0,scores,stats,attempts:{},lastAttemptAt:{},categoryHistory:[],usedFingerprints:[],completedFingerprint:'',historyRecorded:false,readyPlayers:[],readyDeadline:0,winner:'',nextAt:0,cancelled:false};log(room,`상식 퀴즈를 시작합니다. ${settings.questionCount?`${settings.questionCount}문제`:'무한 모드'} · 답은 아래 입력창에 작성해 주세요.`);supplyNextQuestion(room,now);}
function finish(room:Room,cancelled=false){const state=room.quiz!;state.stage='finished';state.deadline=0;state.cancelled=cancelled;const elapsed=Math.max(1,Date.now()-(state.openedAt||Date.now()));void elapsed;const lines=state.players.map(player=>{const stats=state.stats[player.id],average=stats.correct?Math.round(stats.responseTotal/stats.correct/100)/10:0;return `${player.name} ${state.scores[player.id]}점 · 정답 ${stats.correct} · 오답 ${stats.wrong} · 평균 ${average}초 · 최고 연속 ${stats.bestStreak}`;});log(room,`상식 퀴즈 ${cancelled?'종료':'결과'}\n${lines.join('\n')}`);}
export function stopQuiz(room:Room){if(activeQuiz(room))finish(room,true);}
export function supplyNextQuestion(room:Room,now:number,question?:QuizQuestion){const state=room.quiz!;if(state.questionCount&&state.number>=state.questionCount){finish(room);return;}let next=question??state.queue[state.cursor++];while(next&&retiredQuizQuestion(next))next=state.queue[state.cursor++];if(!next){state.stage='loading';state.deadline=0;return;}openQuestion(room,next,now);}
export function markQuestionReady(room:Room,token:string,now:number){const state=room.quiz;if(!state||state.stage!=='ready'||!state.players.some(player=>player.id===token))return false;if(!state.readyPlayers.includes(token))state.readyPlayers.push(token);if(state.readyPlayers.length===state.players.length)beginQuestion(state,now);return true;}
function points(state:QuizState){return state.hintStage===0?quizConfig.points.beforeHint:state.hintStage===1?quizConfig.points.afterChoseong:quizConfig.points.afterExtraHint;}
function complete(room:Room,now:number,winner=''){const state=room.quiz!,question=state.current!;state.stage='result';state.winner=winner;state.nextAt=now+quizConfig.resultPauseMs;state.deadline=state.nextAt;state.completedFingerprint=question.fingerprint;state.historyRecorded=false;}
export function submitAnswer(room:Room,token:string,text:string,now:number){const state=room.quiz;if(!state||state.stage!=='question'||!state.current||!state.players.some(player=>player.id===token)||now>=state.deadline)throw new Error('지금은 답을 제출할 수 없습니다.');const value=text.trim().slice(0,120);if(!value)throw new Error('답을 입력해 주세요.');const last=state.lastAttemptAt[token]??0;if(now-last<quizConfig.answerCooldownMs)throw new Error('잠시 생각한 뒤 다시 답해 주세요.');const attempts=state.attempts[token]??0;if(attempts>=quizConfig.maxAttemptsPerQuestion)throw new Error('이번 문제의 답변 횟수를 모두 사용했습니다.');state.lastAttemptAt[token]=now;state.attempts[token]=attempts+1;const player=state.players.find(item=>item.id===token)!;message(room,player.name,value,false);
 if(isCorrectAnswer(value,state.current.answer,state.current.acceptedAnswers)){const gained=points(state),stats=state.stats[token];state.scores[token]+=gained;stats.correct++;stats.streak++;stats.bestStreak=Math.max(stats.bestStreak,stats.streak);stats.responseTotal+=now-state.openedAt;log(room,`정답입니다. ${player.name}님 +${gained}점\n정답: ${state.current.answer}`);complete(room,now,token);return true;}
 const stats=state.stats[token];stats.wrong++;stats.streak=0;log(room,'오답입니다.');return false;
}
export function tickQuiz(room:Room,now:number){const state=room.quiz;if(!state||!activeQuiz(room))return false;let changed=false;if(state.players.some(player=>!room.players.some(current=>current.id===player.id))){finish(room,true);log(room,'참여자가 나가 게임을 종료했습니다.');return true;}
 if(state.stage==='ready'&&now>=state.readyDeadline){beginQuestion(state,now);changed=true;}
 if(state.stage==='question'&&state.current){if(state.hintStage<1&&now>=state.openedAt+quizConfig.choseongAtMs){state.hintStage=1;log(room,`힌트 · ${choseongHint(state.current.answer)}`);changed=true;}if(state.hintStage<2&&now>=state.openedAt+quizConfig.extraHintAtMs){state.hintStage=2;log(room,`추가 힌트 · ${firstLetterHint(state.current.answer)} · ${quizCategoryName(state.current.category)}`);changed=true;}if(now>=state.openedAt+quizConfig.revealAtMs){for(const player of state.players){const stats=state.stats[player.id];stats.wrong++;stats.streak=0;}log(room,`시간이 지났습니다.\n정답: ${state.current.answer}`);complete(room,now);changed=true;}}
 if(state.stage==='result'&&now>=state.nextAt){supplyNextQuestion(room,now);changed=true;}return changed;
}
export function markHistoryRecorded(room:Room){if(room.quiz)room.quiz.historyRecorded=true;}
export function quizView(room:Room,token:string):QuizView|null{const state=room.quiz;if(!state)return null;const participant=state.players.find(player=>player.id===token),current=state.current,showAnswer=state.stage==='result'||state.stage==='finished';return {id:state.id,creator:state.creator.slice(0,8),players:state.players.map(player=>({...player,id:player.id.slice(0,8)})),difficulty:state.difficulty,category:state.category,questionCount:state.questionCount,stage:state.stage,number:state.number,deadline:state.deadline,openedAt:state.openedAt,hintStage:state.hintStage,question:current?.question??'',hint:state.hintStage>=1&&current?choseongHint(current.answer):'',extraHint:state.hintStage>=2&&current?`${firstLetterHint(current.answer)} · ${quizCategoryName(current.category)}`:'',answer:showAnswer?current?.answer??'':'',participating:!!participant,attempts:state.attempts[token]??0,maxAttempts:quizConfig.maxAttemptsPerQuestion,myScore:state.scores[token]??0,scores:state.players.map(player=>({id:player.id.slice(0,8),name:player.name,score:state.scores[player.id]??0})),stats:state.stats[token]??freshStats(),cancelled:state.cancelled};}
