import type {QuizCategory,QuizDifficulty} from './types';
type Fact={question:string;answer:string;accepted?:string[];difficulty:QuizDifficulty;category:Exclude<QuizCategory,'all'>};
// This intentionally small emergency set keeps a game playable while external providers are unavailable.
// The durable pool is populated from provider data rather than expanding this list into a bundled question bank.
export const fallbackFacts:Fact[]=[
 {question:'대한민국의 수도는 어디일까요?',answer:'서울',difficulty:'elementary',category:'geography'},
 {question:'태양계에서 가장 큰 행성은 무엇일까요?',answer:'목성',difficulty:'elementary',category:'science'},
 {question:'물이 어는 온도는 섭씨 몇 도일까요?',answer:'0도',accepted:['0','영도'],difficulty:'elementary',category:'science'},
 {question:'지구의 유일한 자연 위성은 무엇일까요?',answer:'달',difficulty:'elementary',category:'science'},
 {question:'세계에서 가장 넓은 바다는 어디일까요?',answer:'태평양',difficulty:'elementary',category:'geography'},
 {question:'훈민정음을 창제한 조선의 왕은 누구일까요?',answer:'세종대왕',accepted:['세종'],difficulty:'elementary',category:'history'},
 {question:'삼각형의 변은 모두 몇 개일까요?',answer:'3개',accepted:['3','세 개'],difficulty:'elementary',category:'general'},
 {question:'해가 뜨는 방향은 어디일까요?',answer:'동쪽',accepted:['동'],difficulty:'elementary',category:'general'},
 {question:'일본의 수도는 어디일까요?',answer:'도쿄',accepted:['동경'],difficulty:'elementary',category:'geography'},
 {question:'사람이 숨을 쉴 때 꼭 필요한 기체는 무엇일까요?',answer:'산소',difficulty:'elementary',category:'science'},
 {question:'우리나라의 국기는 무엇이라고 부를까요?',answer:'태극기',difficulty:'elementary',category:'culture'},
 {question:'육지에서 가장 빠른 동물은 무엇일까요?',answer:'치타',difficulty:'elementary',category:'science'},
 {question:'프랑스의 수도는 어디일까요?',answer:'파리',difficulty:'middle',category:'geography'},
 {question:'우리나라 최초의 한글 소설로 알려진 작품은 무엇일까요?',answer:'홍길동전',difficulty:'middle',category:'literature'},
 {question:'혈액을 온몸으로 내보내는 기관은 무엇일까요?',answer:'심장',difficulty:'middle',category:'science'},
 {question:'조선을 건국한 인물은 누구일까요?',answer:'이성계',accepted:['태조'],difficulty:'middle',category:'history'},
 {question:'제2차 세계 대전이 끝난 해는 몇 년일까요?',answer:'1945년',accepted:['1945'],difficulty:'middle',category:'history'},
 {question:'적도를 나타내는 위도는 몇 도일까요?',answer:'0도',accepted:['0','영도'],difficulty:'middle',category:'geography'},
 {question:'희곡 로미오와 줄리엣을 쓴 작가는 누구일까요?',answer:'윌리엄 셰익스피어',accepted:['셰익스피어'],difficulty:'middle',category:'literature'},
 {question:'우리나라의 삼권 분립에서 권력은 몇 가지로 나뉠까요?',answer:'3개',accepted:['3','세 개'],difficulty:'middle',category:'society'},
 {question:'식물이 빛을 이용해 양분을 만드는 작용은 무엇일까요?',answer:'광합성',difficulty:'middle',category:'science'},
 {question:'지구에서 가장 큰 대륙은 어디일까요?',answer:'아시아',accepted:['아시아 대륙'],difficulty:'middle',category:'geography'},
 {question:'교향곡 운명을 작곡한 음악가는 누구일까요?',answer:'베토벤',accepted:['루트비히 판 베토벤'],difficulty:'middle',category:'art'},
 {question:'한글날은 몇 월 며칠일까요?',answer:'10월 9일',accepted:['10월9일','1009'],difficulty:'middle',category:'culture'},
 {question:'경제에서 물가가 지속적으로 오르는 현상을 무엇이라고 할까요?',answer:'인플레이션',difficulty:'high',category:'society'},
 {question:'산성도에서 중성을 나타내는 pH 값은 얼마일까요?',answer:'7',accepted:['7.0'],difficulty:'high',category:'science'},
 {question:'고려를 건국한 인물은 누구일까요?',answer:'왕건',accepted:['태조 왕건','태조'],difficulty:'high',category:'history'},
 {question:'소설 죄와 벌을 쓴 작가는 누구일까요?',answer:'도스토옙스키',accepted:['표도르 도스토옙스키'],difficulty:'high',category:'literature'},
 {question:'그림 게르니카를 그린 화가는 누구일까요?',answer:'파블로 피카소',accepted:['피카소'],difficulty:'high',category:'art'},
 {question:'세포에서 에너지를 생산하는 소기관은 무엇일까요?',answer:'미토콘드리아',difficulty:'high',category:'science'},
 {question:'사회 계약론을 쓴 사상가는 누구일까요?',answer:'장 자크 루소',accepted:['루소'],difficulty:'high',category:'society'},
 {question:'웹 주소에서 HTTPS의 마지막 S가 뜻하는 영어 단어는 무엇일까요?',answer:'Secure',accepted:['secure','시큐어'],difficulty:'high',category:'technology'},
 {question:'컴퓨터에서 명령을 해석하고 연산을 처리하는 핵심 장치의 약자는 무엇일까요?',answer:'CPU',accepted:['cpu','중앙처리장치'],difficulty:'high',category:'technology'},
 {question:'수요가 증가하고 공급이 같을 때 일반적으로 가격은 어떻게 될까요?',answer:'상승',accepted:['오른다','상승한다'],difficulty:'high',category:'society'},
 {question:'국제 단위계에서 전류의 기본 단위는 무엇일까요?',answer:'암페어',accepted:['A','ampere'],difficulty:'high',category:'science'},
 {question:'대기권에서 오존층이 주로 위치한 층은 어디일까요?',answer:'성층권',difficulty:'high',category:'science'},
 {question:'정언명령을 중심 개념으로 제시한 철학자는 누구일까요?',answer:'임마누엘 칸트',accepted:['칸트'],difficulty:'university',category:'society'},
 {question:'국부론을 쓴 경제학자는 누구일까요?',answer:'애덤 스미스',accepted:['아담 스미스','스미스'],difficulty:'university',category:'society'},
 {question:'과학 이론의 반증 가능성을 강조한 철학자는 누구일까요?',answer:'칼 포퍼',accepted:['포퍼'],difficulty:'university',category:'society'},
 {question:'정치철학서 리바이어던을 쓴 인물은 누구일까요?',answer:'토머스 홉스',accepted:['홉스','토마스 홉스'],difficulty:'university',category:'literature'},
 {question:'국가론을 쓴 고대 그리스 철학자는 누구일까요?',answer:'플라톤',difficulty:'university',category:'literature'},
 {question:'오리엔탈리즘을 쓴 학자는 누구일까요?',answer:'에드워드 사이드',accepted:['사이드'],difficulty:'university',category:'literature'},
 {question:'OSI 네트워크 참조 모델은 모두 몇 계층일까요?',answer:'7계층',accepted:['7','7개'],difficulty:'university',category:'technology'},
 {question:'게임 이론에서 내시 균형의 이름이 유래한 수학자는 누구일까요?',answer:'존 내시',accepted:['내시'],difficulty:'university',category:'society'},
 {question:'열역학에서 엔트로피의 SI 단위는 무엇일까요?',answer:'줄 매 켈빈',accepted:['J/K','줄/켈빈','J K-1'],difficulty:'university',category:'science'},
 {question:'상대성 이론을 발표한 물리학자는 누구일까요?',answer:'알베르트 아인슈타인',accepted:['아인슈타인'],difficulty:'university',category:'science'},
 {question:'프로그래밍 언어 C를 개발한 인물은 누구일까요?',answer:'데니스 리치',accepted:['리치'],difficulty:'university',category:'technology'},
 {question:'죄수의 딜레마가 속하는 학문적 분석 틀은 무엇일까요?',answer:'게임 이론',accepted:['게임이론'],difficulty:'university',category:'society'},
];
