const choseong=['ㄱ','ㄲ','ㄴ','ㄷ','ㄸ','ㄹ','ㅁ','ㅂ','ㅃ','ㅅ','ㅆ','ㅇ','ㅈ','ㅉ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'];
const significant=(value:string)=>[...value].filter(char=>/[\p{L}\p{N}]/u.test(char));
function shapeHint(value:string){const chars=significant(value);if(chars.length&&chars.every(char=>/\p{N}/u.test(char)))return `숫자 ${chars.length}자리`;if(chars.length&&chars.every(char=>/[A-Za-z]/.test(char)))return `영문 ${chars.length}글자`;return null;}
export function normalizeAnswer(value:string){return value.normalize('NFKC').toLocaleLowerCase('ko-KR').replace(/[\s\p{P}\p{S}]+/gu,'');}
export function isCorrectAnswer(value:string,answer:string,accepted:string[]=[]){const normalized=normalizeAnswer(value);return !!normalized&&[answer,...accepted].some(candidate=>normalizeAnswer(candidate)===normalized);}
export function choseongHint(value:string){const shape=shapeHint(value);if(shape)return shape;return [...value].map(char=>{const code=char.charCodeAt(0);return code>=0xac00&&code<=0xd7a3?choseong[Math.floor((code-0xac00)/588)]:/[\p{L}\p{N}]/u.test(char)?'□':' ';}).join('').replace(/ +/g,' ').trim();}
export function firstLetterHint(value:string){const shape=shapeHint(value),chars=significant(value);if(shape?.startsWith('숫자')||shape&&chars.length===1)return shape;let revealed=false;return [...value].map(char=>{if(/\s/u.test(char))return char;if(/\p{N}/u.test(char))return '□';if(!revealed&&/\p{L}/u.test(char)){revealed=true;return char;}return /[가-힣]/u.test(char)?'○':/\p{L}/u.test(char)?'•':char;}).join('');}
export function normalizedQuestion(value:string){return value.normalize('NFKC').toLocaleLowerCase('ko-KR').replace(/<[^>]*>/g,' ').replace(/[\s\p{P}\p{S}]+/gu,'');}
export async function questionFingerprint(value:string){const bytes=new TextEncoder().encode(normalizedQuestion(value));const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(byte=>byte.toString(16).padStart(2,'0')).join('');}
