import {quizConfig,retiredQuizQuestion} from './config';
import {fallbackFacts} from './fallback';
import {questionFingerprint} from './normalize';
import {quizProviders} from './providers/registry';
import type {QuizQuestion,QuizSettings} from './types';
import type {D1Database} from '@cloudflare/workers-types';
type QuestionRow={id:string;provider:string;provider_question_id:string|null;question:string;answer:string;accepted_answers:string;difficulty:QuizQuestion['difficulty'];category:QuizQuestion['category'];source:string;fingerprint:string;use_count:number};
function rowQuestion(row:QuestionRow):QuizQuestion{return {id:row.id,provider:row.provider,providerQuestionId:row.provider_question_id,question:row.question,answer:row.answer,acceptedAnswers:JSON.parse(row.accepted_answers) as string[],difficulty:row.difficulty,category:row.category,source:row.source,fingerprint:row.fingerprint};}
async function complete(question:Omit<QuizQuestion,'id'|'fingerprint'>):Promise<QuizQuestion>{const fingerprint=await questionFingerprint(question.question);return {...question,id:`${question.provider}:${question.providerQuestionId??fingerprint.slice(0,20)}`,fingerprint};}
function quality(question:QuizQuestion){return question.question.length>=5&&question.question.length<=quizConfig.maxQuestionLength&&question.answer.length>0&&question.answer.length<=quizConfig.maxAnswerLength&&!/<[^>]+>|&(?:[a-z]+|#\d+);/i.test(question.question+question.answer)&&!/(현재|요즘|가장 부자인|대통령은 누구)/.test(question.question);}
async function insertQuestions(db:D1Database,questions:QuizQuestion[]){const now=Date.now(),statements=questions.filter(quality).map(question=>db.prepare('INSERT OR IGNORE INTO quiz_questions(id,provider,provider_question_id,question,answer,accepted_answers,difficulty,category,source,fingerprint,fetched_at,use_count) VALUES(?,?,?,?,?,?,?,?,?,?,?,0)').bind(question.id,question.provider,question.providerQuestionId,question.question,question.answer,JSON.stringify(question.acceptedAnswers),question.difficulty,question.category,question.source,question.fingerprint,now));if(statements.length)await db.batch(statements);}
export async function seedFallback(db:D1Database){const questions=await Promise.all(fallbackFacts.map((fact,index)=>complete({provider:'fallback',providerQuestionId:String(index+1),question:fact.question,answer:fact.answer,acceptedAnswers:fact.accepted??[],difficulty:fact.difficulty,category:fact.category,source:'bundled emergency cache'})));await insertQuestions(db,questions);await db.batch(questions.map(question=>db.prepare('UPDATE quiz_questions SET question=?,answer=?,accepted_answers=?,difficulty=?,category=?,source=?,fingerprint=?,fetched_at=? WHERE id=?').bind(question.question,question.answer,JSON.stringify(question.acceptedAnswers),question.difficulty,question.category,question.source,question.fingerprint,Date.now(),question.id)));}
export async function removeRetiredQuestions(db:D1Database){const result=await db.prepare("DELETE FROM quiz_questions WHERE provider='wikidata' AND (provider_question_id LIKE 'currency:%' OR provider_question_id LIKE 'elementSymbol:%' OR provider_question_id LIKE 'atomicNumber:%')").run();return Number(result.meta.changes??0);}
export async function ensureQuestionPool(db:D1Database,force=false){
 if(await removeRetiredQuestions(db))force=true;await seedFallback(db);const now=Date.now();const counts=await db.prepare('SELECT difficulty,count(*) AS count FROM quiz_questions GROUP BY difficulty').all<{difficulty:string;count:number}>();const countMap=new Map(counts.results.map(row=>[row.difficulty,Number(row.count)]));const states=await db.prepare('SELECT provider,refreshed_at,last_error FROM quiz_provider_state').all<{provider:string;refreshed_at:number;last_error:string|null}>();const playable=quizConfig.difficulties.every(item=>(countMap.get(item.id)??0)>=quizConfig.playableFloorPerDifficulty);
 const successful=states.results.filter(row=>!row.last_error).reduce((latest,row)=>Math.max(latest,Number(row.refreshed_at)),0),attempted=states.results.reduce((latest,row)=>Math.max(latest,Number(row.refreshed_at)),0);
 if(!force&&playable&&((successful&&now-successful<quizConfig.refreshAfterMs)||(attempted&&now-attempted<quizConfig.providerRetryAfterMs)))return;
 for(const provider of quizProviders){if(!provider.enabledByDefault)continue;const saved=await db.prepare('SELECT token FROM quiz_provider_state WHERE provider=?').bind(provider.id).first<{token:string|null}>();let token=saved?.token??null,error='';try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),quizConfig.providerTimeoutMs);const result=await provider.fetchQuestions({limit:quizConfig.targetPoolPerDifficulty*2,token,signal:controller.signal});clearTimeout(timer);token=result.token??token;const questions=await Promise.all(result.questions.map(complete));await insertQuestions(db,questions);}catch(e){error=e instanceof Error?e.message.slice(0,160):'provider error';}
  await db.prepare('INSERT INTO quiz_provider_state(provider,token,refreshed_at,last_error) VALUES(?,?,?,?) ON CONFLICT(provider) DO UPDATE SET token=excluded.token,refreshed_at=excluded.refreshed_at,last_error=excluded.last_error').bind(provider.id,token,now,error).run();
 }
}
function shuffle<T>(values:T[]){for(let i=values.length-1;i>0;i--){const random=crypto.getRandomValues(new Uint32Array(1))[0]/4294967296,j=Math.floor(random*(i+1));[values[i],values[j]]=[values[j],values[i]];}return values;}
export async function selectQuestions(db:D1Database,settings:QuizSettings,tokens:string[],count:number,excluded:string[]=[]){
 const where=settings.category==='all'?'difficulty=?':'difficulty=? AND category=?',params=settings.category==='all'?[settings.difficulty]:[settings.difficulty,settings.category];const rows=await db.prepare(`SELECT * FROM quiz_questions WHERE ${where} ORDER BY use_count ASC,last_used_at ASC LIMIT 500`).bind(...params).all<QuestionRow>();rows.results=rows.results.filter(row=>!retiredQuizQuestion({provider:row.provider,providerQuestionId:row.provider_question_id}));if(!rows.results.length)return [];
 const placeholders=tokens.map(()=>'?').join(','),history=tokens.length?await db.prepare(`SELECT fingerprint,max(seen_at) AS seen_at FROM quiz_history WHERE token IN (${placeholders}) GROUP BY fingerprint`).bind(...tokens).all<{fingerprint:string;seen_at:number}>():{results:[]};const seen=new Map(history.results.map(row=>[row.fingerprint,Number(row.seen_at)])),cutoff=Date.now()-quizConfig.historyCooldownDays*86400000,blocked=new Set(excluded);
 const rank=(row:QuestionRow)=>!seen.has(row.fingerprint)?0:(seen.get(row.fingerprint)??0)<cutoff?1:2;const selected:QuestionRow[]=[];for(const level of [0,1,2]){const candidates=shuffle(rows.results.filter(row=>rank(row)===level&&!blocked.has(row.fingerprint)));const buckets=new Map<string,QuestionRow[]>();for(const row of candidates)buckets.set(row.category,[...(buckets.get(row.category)??[]),row]);while(selected.length<count&&[...buckets.values()].some(values=>values.length)){for(const values of buckets.values()){const row=values.shift();if(row&&!blocked.has(row.fingerprint)){selected.push(row);blocked.add(row.fingerprint);if(selected.length===count)break;}}}if(selected.length===count)break;}
 return selected.map(rowQuestion);
}
export async function recordQuestionHistory(db:D1Database,tokens:string[],fingerprint:string){const now=Date.now(),statements=tokens.map(token=>db.prepare('INSERT INTO quiz_history(token,fingerprint,seen_at) VALUES(?,?,?) ON CONFLICT(token,fingerprint) DO UPDATE SET seen_at=excluded.seen_at').bind(token,fingerprint,now));statements.push(db.prepare('UPDATE quiz_questions SET use_count=use_count+1,last_used_at=? WHERE fingerprint=?').bind(now,fingerprint));await db.batch(statements);}
